package br.com.natura.segmentation.commons.enumerators

object EngineNames {
  val BASEAPPLICATION: String     = "SEGMENTATION-COMMERCIAL-BASEAPPLICATION"

  val ACTIVES: String             = "SEGMENTATION-COMMERCIAL-ACTIVES"
  val ADJUSTS: String             = "SEGMENTATION-COMMERCIAL-ADJUSTS"
  val BEGINNINGS: String          = "SEGMENTATION-COMMERCIAL-BEGINNINGS"
  val BEGINNINGSCOMPLETE: String  = "SEGMENTATION-COMMERCIAL-BEGINNINGSCOMPLETE"
  val BIRTHDAY: String            = "SEGMENTATION-COMMERCIAL-BIRTHDAY"
  val CYCLES: String              = "SEGMENTATION-COMMERCIAL-CYCLES"
  val FIRSTORDER: String          = "SEGMENTATION-COMMERCIAL-FIRSTORDER"
  val INACTIVES: String           = "SEGMENTATION-COMMERCIAL-INACTIVES"
  val ORDERS: String              = "SEGMENTATION-COMMERCIAL-ORDERS"
  val REGISTERED: String          = "SEGMENTATION-COMMERCIAL-REGISTERED"
  val RESELLER: String            = "SEGMENTATION-COMMERCIAL-RESELLER"
  val STARTERKIT: String          = "SEGMENTATION-COMMERCIAL-STARTERKIT"
  val TITLES: String              = "SEGMENTATION-COMMERCIAL-TITLES"
}